### ISSUE TITLE
CodeforAfrica.org is down

### ISSUE THREAD

**Issue by vickOnRails** [CodeForAfrica/CodeForAfrica.org#30]
**Is your feature request related to a problem? Please describe.**
I visited the official codeforAfrica site a few months ago. I bookmarked it so I could be reminded to contribute to one of the projects sometime. I had a lot of free time this month, so I decided to take a second look. The site was down. 

**Describe the solution you'd like**
I believe there's a lot going on to bring the site back up. I would love to contribute by suggesting a few UX/visual improvements to the old codeforAfrica site. More sincerely, I would love if the site could go through an overhaul considering it was designed 6 years ago. Building it from the ground up will introduce improvements informed by learnings over the time of the project. 

In order to be more concrete, I designed and built a prototype of what could be possible if codeforAfrica underwent an overhaul. (Demo at http://codeforafrica.netlify.com). A detailed WIP case study of the process at (https://www.notion.so/vickonrails/Redesigning-The-CodeForAfrica-Site-73dce750969b4079a64764af899bb649)

**Describe alternatives you've considered**
The prototype is a suggestion of what the site could look like and things could build onwards. If the prototype doesn't look or feel right, I'd be eager to assist in any possible to make what you currently have better. 

**Additional context**
I've tried reaching out to a few members of the codeforAfrica team concerning why the site is down, but none has spoken back to me. If there's any reason why my contribution can't be accepted, I'd love to know beforehand. 

Plus: I'm a Product Designer from Nigeria. You can check see my work at [victorofoegbu.com](victorofoegbu.com) and [victorofoegbu.design](victorofoegbu.design)

**Comment by DavidLemayian** [comment]
Hey @vickOnRails . Thank you for reaching out and thank you for taking so much time to work to help us have an updated site. It is genuinely heartwarming and amazing to see the amount of effort you put into this.

We're working on new designs for the website at the moment so will be able to update the main site once that is done. Otherwise, I'd like to invite you to our Slack community of experts to share your tech and data journalism experiences with the rest and perhaps learn from them too (e-mail should be in your inbox). I'd also like to encourage you to keep us updated on what you're up to.

Wishing you an amazing rest of the day ahead.

**Comment by vickOnRails** [comment]
Thanks for the reply, David. 
I guess this means I 'll do away with what I've worked on. 

Alright then. A huge thanks for the slack invite.
